name: Check lint, format and build on Pull Request
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8.9.0
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Run linter and prettier
        run: |
          pnpm lint
          pnpm format

      - name: Build
        run: pnpm build
